/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R403RouteImport } from './routes/403'
import { Route as R404RouteImport } from './routes/404'
import { Route as R500RouteImport } from './routes/500'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArcadeRouteImport } from './routes/arcade'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HireMeRouteImport } from './routes/hire-me'
import { Route as RecordRouteImport } from './routes/record'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AppsIndexRouteImport } from './routes/apps.index'
import { Route as AppsSlugRouteImport } from './routes/apps.$slug'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as FreelanceIndexRouteImport } from './routes/freelance.index'
import { Route as FreelanceSlugRouteImport } from './routes/freelance.$slug'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const R500Route = R500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArcadeRoute = ArcadeRouteImport.update({
  id: '/arcade',
  path: '/arcade',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HireMeRoute = HireMeRouteImport.update({
  id: '/hire-me',
  path: '/hire-me',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsIndexRoute = AppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsSlugRoute = AppsSlugRouteImport.update({
  id: '/apps/$slug',
  path: '/apps/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceIndexRoute = FreelanceIndexRouteImport.update({
  id: '/freelance/',
  path: '/freelance/',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceSlugRoute = FreelanceSlugRouteImport.update({
  id: '/freelance/$slug',
  path: '/freelance/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/hire-me': typeof HireMeRoute
  '/record': typeof RecordRoute
  '/resume': typeof ResumeRoute
  '/services': typeof ServicesRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/freelance/$slug': typeof FreelanceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/freelance/': typeof FreelanceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/hire-me': typeof HireMeRoute
  '/record': typeof RecordRoute
  '/resume': typeof ResumeRoute
  '/services': typeof ServicesRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/freelance/$slug': typeof FreelanceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/apps': typeof AppsIndexRoute
  '/blog': typeof BlogIndexRoute
  '/freelance': typeof FreelanceIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/404': typeof R404Route
  '/500': typeof R500Route
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/arcade': typeof ArcadeRoute
  '/certificates': typeof CertificatesRoute
  '/contact': typeof ContactRoute
  '/hire-me': typeof HireMeRoute
  '/record': typeof RecordRoute
  '/resume': typeof ResumeRoute
  '/services': typeof ServicesRoute
  '/apps/$slug': typeof AppsSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/freelance/$slug': typeof FreelanceSlugRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/apps/': typeof AppsIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/freelance/': typeof FreelanceIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/about'
    | '/admin'
    | '/arcade'
    | '/certificates'
    | '/contact'
    | '/hire-me'
    | '/record'
    | '/resume'
    | '/services'
    | '/apps/$slug'
    | '/blog/$slug'
    | '/freelance/$slug'
    | '/projects/$slug'
    | '/apps/'
    | '/blog/'
    | '/freelance/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/about'
    | '/admin'
    | '/arcade'
    | '/certificates'
    | '/contact'
    | '/hire-me'
    | '/record'
    | '/resume'
    | '/services'
    | '/apps/$slug'
    | '/blog/$slug'
    | '/freelance/$slug'
    | '/projects/$slug'
    | '/apps'
    | '/blog'
    | '/freelance'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/404'
    | '/500'
    | '/about'
    | '/admin'
    | '/arcade'
    | '/certificates'
    | '/contact'
    | '/hire-me'
    | '/record'
    | '/resume'
    | '/services'
    | '/apps/$slug'
    | '/blog/$slug'
    | '/freelance/$slug'
    | '/projects/$slug'
    | '/apps/'
    | '/blog/'
    | '/freelance/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  R404Route: typeof R404Route
  R500Route: typeof R500Route
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ArcadeRoute: typeof ArcadeRoute
  CertificatesRoute: typeof CertificatesRoute
  ContactRoute: typeof ContactRoute
  HireMeRoute: typeof HireMeRoute
  RecordRoute: typeof RecordRoute
  ResumeRoute: typeof ResumeRoute
  ServicesRoute: typeof ServicesRoute
  AppsSlugRoute: typeof AppsSlugRoute
  BlogSlugRoute: typeof BlogSlugRoute
  FreelanceSlugRoute: typeof FreelanceSlugRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  AppsIndexRoute: typeof AppsIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FreelanceIndexRoute: typeof FreelanceIndexRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/500': {
      id: '/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof R500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arcade': {
      id: '/arcade'
      path: '/arcade'
      fullPath: '/arcade'
      preLoaderRoute: typeof ArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire-me': {
      id: '/hire-me'
      path: '/hire-me'
      fullPath: '/hire-me'
      preLoaderRoute: typeof HireMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/': {
      id: '/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AppsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps/$slug': {
      id: '/apps/$slug'
      path: '/apps/$slug'
      fullPath: '/apps/$slug'
      preLoaderRoute: typeof AppsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/': {
      id: '/freelance/'
      path: '/freelance'
      fullPath: '/freelance/'
      preLoaderRoute: typeof FreelanceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance/$slug': {
      id: '/freelance/$slug'
      path: '/freelance/$slug'
      fullPath: '/freelance/$slug'
      preLoaderRoute: typeof FreelanceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  R404Route: R404Route,
  R500Route: R500Route,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ArcadeRoute: ArcadeRoute,
  CertificatesRoute: CertificatesRoute,
  ContactRoute: ContactRoute,
  HireMeRoute: HireMeRoute,
  RecordRoute: RecordRoute,
  ResumeRoute: ResumeRoute,
  ServicesRoute: ServicesRoute,
  AppsSlugRoute: AppsSlugRoute,
  BlogSlugRoute: BlogSlugRoute,
  FreelanceSlugRoute: FreelanceSlugRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  AppsIndexRoute: AppsIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  FreelanceIndexRoute: FreelanceIndexRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
